name = "ParetoRecipes"
uuid = "71a409db-0c41-4225-8938-aaf295661ce5"
authors = ["Saketh Rama"]
version = "0.0.1"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
RecipesBase = "1"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
